version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_registration_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - event_network

  webserver:
    image: nginx:alpine
    container_name: event_registration_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - event_network

  database:
    image: mysql:8.0
    container_name: event_registration_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: event_registration
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - event_network

  redis:
    image: redis:alpine
    container_name: event_registration_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - event_network

networks:
  event_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
